avahi/avahi

- avahi-autoipd/main.c
during the probe phase avahi-autoipd must only select a new IP when
it receives an ARP Probe packet:
According to RFC3927, Section 2.2.1. Probe details:
> An ARP Request constructed this way with an all-zero 'sender IP 
> address' is referred to as an "ARP Probe".
and
> In addition, if during this period [checking if an address is already 
> in use] the host receives any ARP Probe where the packet's 'target IP
> address' is the address being probed for, and the packet's 'sender
> hardware address' is not the hardware address of the interface the
> host is attempting to configure, then the host MUST similarly treat
> this as an address conflict and select a new address as above.
When receiving an ARP packet during probe avahi-autoipd did not check
if the 'sender IP address' is all-zero and …
> avahi-autoipd: only consider ARP Probe packets

- configure.ac
This only affected the report at the end of configure.
> configure.ac: Fix libavahi-client test

- avahi-common/simple-watch.c
- avahi-common/simple-watch.h
- avahi-common/thread-watch.c
- avahi-common/thread-watch.h
- avahi-common/watch.h
poll.h is defined in POSIX and has existed since at least SUSv2.
Usage of sys/poll.h is a glibc-ism and produces warnings on musl, even
though they are the same header; the only difference is that poll.h
is guaranteed portable due to its standardization.
> Fix warnings on musl libc

- autogen.sh
This allows the build pattern:
git clone …
mkdir /tmp/build
cd /tmp/build
/path/to/checkout/autogen.sh
make
which is useful for builddir ≠ srcdir setups, such as buildbots.
> build: Allow autogen.sh to be run from another directory

- avahi-gobject/AvahiCore-0.6.gir
openSUSE uses a dependency extractor for g-i typelibs that lists which shared libraries are referenced.
It was observed if the linking is not done the right way, generally we end up with weird dependencies (which g-i internally seems to somehow guess until it finds something that works).
Putting the right reference in place makes those things work (mageia uses the same extractor, fedora was discussing it)
> g-i: reference the build shared object from the .gir file

- service-type-database/Makefile.am
pkgdata_DATA is never used - it's pkglibdata_DATA in the other cases
> Do not create a directory below /usr/share which does not have content

- configure.ac
on modern, systemd based systems, the default directory is /run, no longer /var/run
> Move to /run

- avahi-gobject/ga-client.c
- avahi-gobject/ga-client.h
At first I was thinking about using
g_main_context_get_thread_default() instead of NULL in
ga_client_start(), but that would probably break other apps that
expect that client will be always running in the global default main
context.
> gobject: allow using custom context

- avahi-autoipd/avahi-autoipd.action.linux
Delete any IP addresses set to the avahi alias/label before setting a new
so we do not end-up with multiple IP addresses
See https://github.com/lathiat/avahi/issues/111
Signed-off-by: Cedric Hombourger <Cedric_Hombourger@mentor.com>
> avahi-autoipd: clear previously set address before binding a new one

- avahi-glib/glib-watch.c
When an AvahiWatch instance `w` is freed by watch_free(), watch_free()
is supposed to set `w->glib_poll->watch_req_cleanup = TRUE` to trigger
cleanup_watches() during prepare_func(), but instead it incorrectly sets
`w->glib_poll->timeout_req_cleanup = TRUE`. Without invoking
cleanup_watches(), the AvahiWatch instance isn't properly destroyed and
its associated GSource instance isn't removed. The watch callback could
potentially be invoked inappropriately on the supposedly dead watch.
> Fix watch cleanup issue in watch_free.

- avahi-daemon/avahi-service.dtd
- avahi-daemon/static-services.c
- man/avahi.service.5.xml.in
This adds an attribute to the txt-record tag that describes the format
of the value part in the key=value part. For backwards-compatibility
it defaults to text if not specified. Other options include decoding
the value from hex encoding or from base64 encoding. That way we can
specify binary data in an XML file, that normally does not allow
arbitrary bytes in its contents.
These encodings result in larger data than the resulting binary data,
but that should not be a problem - TXT records ought to be small
anyway.
We need that for https://github.com/ostreedev/ostree/pull/782 where we want to send a small bloom filter as the txt record. Encoding that with base64 unnecessarily shortens the filter by 25%.
This is the alternative proposal to https://github.com/lathiat/avahi/pull/84 - the …
> Add support for binary values in TXT records in service files

- .gitignore
- avahi-python/avahi/.gitignore
- avahi-python/avahi/Makefile.am
- avahi-python/avahi/__init__.py
- avahi-python/avahi/test.py
Previously, we would effectively encode anything representable in
Latin-1 as Latin-1, and crash on anything not representable in Latin-1:
>>> import avahi
>>> avahi.string_to_byte_array(u'©')
[dbus.Byte(169)]
>>> avahi.string_to_byte_array(u'\ufeff')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python2.7/dist-packages/avahi/__init__.py", line 94, in string_to_byte_array
r.append(dbus.Byte(ord(c)))
ValueError: Integer outside range 0-255
This is particularly important for Python 3, where the str type
is a Unicode string.
The b'' syntax for bytestrings is supported since at least Python 2.7.
These functions now accept either Unicode strings (Python 2 unicode,
Python 3 str), which are encoded in UTF-8, or bytestrings
(Python 2 str, Python 3 bytes) …
> avahi-python: Encode unicode strings as UTF-8

- avahi-python/avahi/Makefile.am
- avahi-python/avahi/ServiceTypeDatabase.py.in
- configure.ac
- service-type-database/.gitignore
- service-type-database/Makefile.am
- service-type-database/build-db
Also fixes configure failing if Python 3 is the build python and GDBM is
enabled, since Py3 only has anydbm under the name of 'dbm'.
Not enough to make ServiceTypeDatabase.py compatible with Py3, but it's
a start.
> avahi-python: Use the agnostic DBM interface

- .gitignore
- .travis.yml
- Makefile.am
- autogen.sh
- avahi-python/avahi-discover/Makefile.am
- avahi-python/avahi-discover/avahi-discover.desktop.in.in
- avahi-ui/Makefile.am
- avahi-ui/bssh.desktop.in.in
- avahi-ui/bvnc.desktop.in.in
- common/.gitignore
- common/Makefile.am
- configure.ac
- po/.gitignore
- po/Makevars
- po/POTFILES.in
This patch changes the build scripts to use `gettext` for i18n strings extraction and merging in place of `intltool`. This allow dropping the dependency to `intltool`.
Fixes: https://github.com/lathiat/avahi/issues/217
Closes: https://github.com/lathiat/avahi/pull/22
> Migrate from intltool to gettext

- avahi-common/dbus.h
- avahi-core/avahi-test.c
- avahi-core/browse-dns-server.c
- avahi-core/browse-domain.c
- avahi-core/browse-service-type.c
- avahi-core/browse-service.c
- avahi-core/browse.c
- avahi-core/dns-srv-rr.h
- avahi-core/lookup.h
- avahi-core/resolve-address.c
- avahi-core/resolve-host-name.c
- avahi-core/resolve-service.c
- avahi-daemon/dbus-async-address-resolver.c
- avahi-daemon/dbus-async-host-name-resolver.c
- avahi-daemon/dbus-async-service-resolver.c
- avahi-daemon/dbus-domain-browser.c
- avahi-daemon/dbus-internal.h
- avahi-daemon/dbus-protocol.c
- avahi-daemon/dbus-record-browser.c
- avahi-daemon/dbus-service-browser.c
- avahi-daemon/dbus-service-type-browser.c
- avahi-daemon/org.freedesktop.Avahi.AddressResolver.xml
- avahi-daemon/org.freedesktop.Avahi.DomainBrowser.xml
- avahi-daemon/org.freedesktop.Avahi.HostNameResolver.xml
- avahi-daemon/org.freedesktop.Avahi.RecordBrowser.xml
- avahi-daemon/org.freedesktop.Avahi.Server.xml
- avahi-daemon/org.freedesktop.Avahi.ServiceBrowser.xml
- avahi-daemon/org.freedesktop.Avahi.ServiceResolver.xml
- avahi-daemon/org.freedesktop.Avahi.ServiceTypeBrowser.xml
This pull request implements the API change mentioned in #173
> New D-Bus API

- avahi-common/strlst-test.c
- avahi-common/strlst.c
This PR addresses issues #169 and #144, by causing `avahi_string_list_to_string` to escape double-quotes and backslashes with a leading backslash and to escape control bytes using a decimal representation.
I (quickly) checked callers of `avahi_string_list_to_string`, and it looks like in all contexts producing escaped output is a reasonable thing to do.
I have run `strlst-test` with valgrind, which reported no problems.
The patch uses *decimal* escapes (just like escaped labels), using them for control bytes strictly less than 32. This lets naive parsers of `avahi-browse -p` output work line-by-line, and allows correct representation of e.g. embedded NUL bytes.
| input                           |  buggy current output (unpatched) | output (this patch) |
| ----- | ------------------ | …
> avahi-common: Repair avahi_string_list_to_string to escape embedded quotes and backslashes.

- avahi-daemon/static-services.c
That's a regression that came with 3b067e06b274 ("Add support for
binary values in TXT records in service files"), we dropped the NULL
check for the strlen call. Other txt record types already check for
NULL value in the decode functions.
Reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882386
> Fix a crash when txt records has an empty value

- avahi-python/avahi-discover/avahi-discover.py
`dict.has_key()` has been deprecated in python3, as per the release docs: https://docs.python.org/3.0/whatsnew/3.0.html#builtins
This pull request updates uses of `has_key` to use python's `in` syntax, which I've checked is backwards compatible with python 2.7.
Note that I needed this change because I'm building on arch linux with this PKGBUILD: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/avahi
However AFAICT this will fix the following exception for anyone with python3 as the default on their system:
```
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
self._handler(*args, **kwargs)
File "/usr/bin/avahi-discover", …
```
> Replace deprecated python `has_key` function with `in` syntax

- avahi-core/server.c
Consider the following setup:
```
+---------+               +--------+
|  host1  |               | host2  |
|         |               |        |
---------+ eth1    |               |        |
|         |               |        |
|    eth0 +---------------+ eth0   |
+---------+               +--------+
```
where `host1` is set as a reflector.
Without this PR, the Resource Records responses coming from `host2` are stored on two caches: on the cache associated with `eth0` (correct), and on the cache associated with `eth1` (wrong).
The RR responses associated with one interface should not be cached on the other interface in the case of a reflector. Otherwise, when `host2` is probing for duplicates (for example after bringing `eth0` down and then up again), it would get old, and possibly wrong …
> Do not cache responses generated locally

- man/avahi-autoipd.8.xml.in
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840833
> man: fix reference to avahi-autoipd.action(8) in avahi-autoipd(8)

- man/Makefile.am
The bshell binary is missing a symlink to its manual page. It should be
symlinked to the man page for bssh, just like how the bvnc man page is.
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=655190
> man: add missing bshell.1 symlink

- man/Makefile.am
These manpages went missing when you disabled gtk2 builds....
> Ship avahi-discover(1), bssh(1) and bvnc(1) also for GTK3

- avahi-libevent.pc.in
When you build rpm with avahi-0.8 and libevent enabled then you will end up in broken rpm requires on non-existing "pkgconfig(libevent-2.1.5)"
```
DEBUG util.py:587:  cooker_main_release                              14 kB/s | 2.5 kB     00:00    
DEBUG util.py:587:  cooker_main_release                             1.5 MB/s |  12 MB     00:08    
DEBUG util.py:587:  cooker_main_updates                              21 kB/s | 1.5 kB     00:00    
DEBUG util.py:585:  BUILDSTDERR: Error: 
DEBUG util.py:585:  BUILDSTDERR:  Problem: conflicting requests
DEBUG util.py:585:  BUILDSTDERR:   - nothing provides pkgconfig(libevent-2.1.5) needed by lib64avahi-libevent-devel-0.8-1.x86_64
DEBUG util.py:587:  (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best …
```
> fix requires in pc file

- avahi-python/avahi-discover/avahi-discover.py
On a Debian system with `fr_CA.UTF-8` locale, I got UnicodeDecodeErrors when trying to select any item in the tree view shown by avahi-discover.
I found out that the translated strings use non-breaking spaces before punctuation, but these strings are bytestrings rather than text (unicode) strings, which causes line 247/250 to fail (bytes-text mixing in Python leading to implicit conversion to ASCII which fails to handle `\xC2\xA0`).
A proper fix would be to use `ugettext` (would also prepare to switch to Python 3, where gettext works in unicode), but it seems that my version of `gettext` module doesn’t have it, so this is a workaround instead.
fixes #158
> Fix bytestring decoding for proper display

- avahi-core/browse-dns-server.c
- avahi-core/browse-domain.c
- avahi-core/browse-service-type.c
- avahi-core/browse-service.c
- avahi-core/browse.c
- avahi-core/resolve-address.c
- avahi-core/resolve-host-name.c
- avahi-core/resolve-service.c
avahi-daemon is crashing when running `ping .local`.
The crash is due to failing assertion from NULL pointer.
Add missing NULL pointer checks to fix it.
Regression introduced in #175
@simoninator @lathiat
> Fix NULL pointer crashes from #175

- avahi-core/timeeventq.c
Reported by Coverity Scan.
I was testing a script sending avahi to Coverity Scan and it was the first warning it threw at me. I think combined with https://github.com/lathiat/avahi/pull/202 it should make Coverity a bit more happy.
> avahi-core: rearrange deallocations in avahi_time_event_queue_new a bit

- avahi-common/Makefile.am
- avahi-glib/Makefile.am
- avahi-libevent/Makefile.am
To get `make check` to run tests automatically they should be added to the TESTS variable: https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html
Unlike functional tests like, say, avahi-test or client-test that should be run in suitable environments those tests are actually unit tests and can safely be run everywhere.
It should make the coverage go from 3% (https://coveralls.io/builds/54821508) to almost 10% (https://coveralls.io/builds/54825736). Admiteddly it isn't much but at least it should cover PRs/patches touching avahi-common and since the testing infrastructure is somewhat ready it should be possible to start adding/extending basic tests or use it to catch obvious regressions automatically.
The PR was tested on aarch64, i386, ppc64le, s390x and …
> tests: run more unit tests automatically

- avahi-daemon/simple-protocol.c
If a client fills the input buffer, client_work() disables the
AVAHI_WATCH_IN event, thus preventing the function from executing the
`read` syscall the next times it is called. However, if the client then
terminates the connection, the socket file descriptor receives a HUP
event, which is not handled, thus the kernel keeps marking the HUP event
as occurring. While iterating over the file descriptors that triggered
an event, the client file descriptor will keep having the HUP event and
the client_work() function is always called with AVAHI_WATCH_HUP but
without nothing being done, thus entering an infinite loop.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=984938
> Avoid infinite-loop in avahi-daemon by handling HUP event in client_work

- avahi-daemon/main.c
We may get signalled to reload / dump data before signal handlers are set up
(in run_server()) and instead get killed as these signals default to
terminate the process.  Instead ignore them until we are ready
Signed-off-by: Peter Korsgaard peter@korsgaard.com
> avahi-daemon: fix SIGHUP/SIGUSR1 race condition at startup

- avahi-qt/Makefile.am
recent commit d1e71b320d96d0f213ecb0885c8313039a09f693 adding QT5
support added a new conditional
but failed to actually set the define.  This commit adds that to
allow successful build when enabling QT3 support
> fix QT3 build

- avahi-common/domain.h
spotted by lintian:
```
W: libavahi-common-dev: national-encoding usr/include/avahi-common/domain.h
N:
N:   A file is not valid UTF-8.
N:
N:   Debian has used UTF-8 for many years. Support for national encodings is being phased out. This file probably appears to users
N:   in mangled characters (also called mojibake).
N:
N:   Packaging control files must be encoded in valid UTF-8.
N:
N:   Please convert the file to UTF-8 using iconv or a similar tool.
```
> Fix encoding of avahi-common/domain.h to be UTF-8

- avahi-daemon/avahi-dbus.conf.in
Looks like the policy wasn't updated when the Server2 interface was introduced.
It's a follow-up to https://github.com/lathiat/avahi/pull/175
@lathiat @pemensik could you take a look?
> dbus: deny SetHostName via org.freedesktop.Avahi.Server2 as well

- .github/workflows/cifuzz.yml
It should help to somewhat excercise the code paths consuming DNS packets under ASan, UBSan and MSan when PRs are opened: https://google.github.io/oss-fuzz/getting-started/continuous-integration/. Other than that it should also help to make sure that new PRs don't break OSS-Fuzz builds.
FWIW I'm planning to move the fuzzing infrastructure to the avahi repository to make it easier to extend the coverage but until then it still should be possible to run the fuzz targets on PRs.
> CI: turn on CIFuzz

- configure.ac
Quoting from [D-Bus 1.14.0 release notes](https://gitlab.freedesktop.org/dbus/dbus/-/blob/dbus-1.14.0/NEWS#L45-51):
> Third-party software should install default dbus policies for the system  bus into `${datadir}/dbus-1/system.d` (this has been supported since dbus 1.10, released in August 2015). Installing default dbus policies in `${sysconfdir}/dbus-1/system.d` is now considered to be deprecated.
> dbus: Use non-deprecated installation path

- configure.ac
Fixes errors like:
```
-ignoreme: warning: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]
+ignoreme: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
void test_broken_ssp(c)
^
```
Signed-off-by: Sam James <sam@gentoo.org>
> configure.ac: fix -Wstrict-prototypes

- avahi-core/iface-linux.c
- avahi-core/iface-pfroute.c
Point-to-point interfaces don't have MULTICAST set on them, since anything other than a unicast is a meaningless concept.
I've back ported this fix to CentOS 8 Stream and avahi-0.7 and it works fine.
Addresses issue #305.
> Logic for p2p on tunnels incorrectly requires IFF_MULTICAST (#305)

- service-type-database/Makefile.am
* build: Include build-db in tarball releases
SCRIPTS are not included in tarballs by default, because they might
be generated from a template. This one isn't, so use the dist_
prefix to distribute it.
Resolves: https://github.com/lathiat/avahi/issues/277
* build: Look for build-db in the srcdir
Otherwise, srcdir != builddir builds (and hence distcheck) will fail.
---
Tested with:
```
make -j5 DISTCHECK_CONFIGURE_FLAGS="--disable-libevent --disable-qt5 --disable-mono --with-systemdsystemunitdir='\$\$dc_install_base/\${systemdsystemunitdir}'" distcheck
```
(I haven't tried distcheck with libevent, Mono or Qt since I don't currently have those installed.)
> Include build-db in tarball releases

- avahi-core/domain-util.c
/etc/lsb-release really isn't used much since systemd started exporting
/etc/os-release. Reuse existing lsb-release parsing code to parse
os-release. This should allow avahi to call hosts without a hostname by
their distribution name, as requested in:
https://bugzilla.redhat.com/show_bug.cgi?id=1392924
> Load distribution name from /etc/os-release

- avahi-daemon/dbus-protocol.c
Back in the day valgrind didn't fully instrument ioctl(SIOCGIFINDEX) and that led to false positives like
https://github.com/lathiat/avahi/issues/34 where valgrind complained about avahi calling that ioctl indirectly via if_nametoindex. Those warnings are long gone so VALGRIND_WORKAROUND can safely be removed.
> avahi-daemon: remove VALGRIND_WORKAROUND

- avahi-common/rlist.h
- avahi-gobject/ga-entry-group.c
- man/avahi.service.5.xml.in
spotted by lintian:
```
I: libavahi-gobject0: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libavahi-gobject.so.0.0.5 uncommited uncommitted
I: avahi-daemon: typo-in-manual-page usr/share/man/man5/avahi.service.5.gz line 13 occurence occurrence
```
> Typo fixes

- avahi-python/avahi-discover/avahi-discover.py
Unicode strings (unicode in Python 2, str or unicode in Python 3) don't
have a decode method; only bytestrings (str or bytes in Python 2,
bytes in Python 3) have that. Decode exactly the strings that need
decoding.
Resolves: https://github.com/lathiat/avahi/issues/275
> avahi-discover: Don't decode unicode strings, only bytestrings

- avahi-common/simple-watch.c
This was causing timeouts to never be removed from the linked list that
tracks them, resulting in both memory and CPU usage to grow larger over
time.
> Do not disable timeout cleanup on watch cleanup

- avahi-core/announce.c
If an interface is no longer relevant for mDNS while an announcer was
probing on this interface, the announcer is removed but the n_probing
counter of the entry group is not updated.   So n_probing would never
reach zero and the entry group would stay  forever in the REGISTERING
state.  If the entry group is for a host resource record,  the daemon
could stay in the registering phase forever and would not publish any
service.
Fix that by decrementing group->n_probing when removing an announcer
in the PROBING state. Also handle the case where the entry group was
waiting for the deleted announcer to become registered.
> Fix not publishing entries if a probing interface is removed.

- avahi-python/avahi-discover/avahi-discover.py
Otherwise, a TXT entry containing a URL with '&' will cause an error.
---
Branch also includes #282, otherwise it would have conflicts with that PR.
> avahi-discover: Escape strings substituted into Pango markup

- fuzz/fuzz-consume-key.c
- fuzz/fuzz-consume-record.c
- fuzz/oss-fuzz.sh
to make it easier to maintain them.
It's prompted by https://github.com/lathiat/avahi/pull/459 where the build script has to be edited to disable libsystemd.
This PR is based on https://github.com/google/oss-fuzz/pull/9107 and
includes all those changes as well:
* the fuzz targets are rewritten in C;
* the build script is changed to use the headers and static libraries
from the the build directory
The license was discussed in https://github.com/google/oss-fuzz/pull/10412#discussion_r1208682267.
~~It's a draft for now. I'll point OSS-Fuzz to this PR to make sure it works.~~ To judge from https://github.com/google/oss-fuzz/pull/10412 it works.
> ci: import the OSS-Fuzz build script and fuzz targets

- .github/dependabot.yml
- .github/workflows/build.sh
- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/differential-shellcheck.yaml
- avahi-compat-howl/Makefile.am
- avahi-compat-libdns_sd/Makefile.am
* ci: turn on coverage reports
* ci: build compat-{howl,libdns_sd} as well
Prompted by https://github.com/lathiat/avahi/pull/465
* make: run the howl and libdns_sd tests automatically
Prompted by https://github.com/lathiat/avahi/pull/465
The coverage went from [9.49%](https://coveralls.io/builds/60369370) to [12.944%](https://coveralls.io/builds/60943442) (but long paths aren't tested)
* ci: no longer rely on autobuild
to get CodeQL to analyze the Python code and the compat libraries
* ci: add shellcheck
Prompted by https://github.com/lathiat/avahi/pull/204
* ci: add dependabot.yml
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> Assorted CI tweaks

- avahi-compat-libdns_sd/warn.c
Fixes copying 1 extra byte which may potentially be outside the buffer if the full program path is long enough.
Using `strlen(slash+1)+1` over the equivalent `strlen(slash)` because it's clearer to read.
> libdns_sd: Fix off-by-one error when copying program name in buffer

- avahi-common/domain.c
- fuzz/fuzz-domain.c
Fixes:
```sh
==93410==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f9e76f14c16 at pc 0x00000047208d bp 0x7ffee90a6a00 sp 0x7ffee90a61c8
READ of size 1110 at 0x7f9e76f14c16 thread T0                                                                                                                 
#0 0x47208c in __interceptor_strlen (out/fuzz-domain+0x47208c) (BuildId: 731b20c1eef22c2104e75a6496a399b10cfc7cba)                    
#1 0x534eb0 in avahi_strdup avahi/avahi-common/malloc.c:167:12
#2 0x53862c in avahi_normalize_name_strdup avahi/avahi-common/domain.c:226:12
```
and
```sh
fuzz-domain: fuzz/fuzz-domain.c:38: int LLVMFuzzerTestOneInput(const uint8_t *, size_t): Assertion `avahi_domain_equal(s, t)' failed.
==101571== ERROR: libFuzzer: deadly signal
#0 0x501175 in …
```
> [common] bail out when escaped labels can't fit into ret

- avahi-core/resolve-service.c
The whole idea of the ServiceResolverPrepare method is that it delays the Found/Failure signals until the client has connected up the D-Bus signal handler. The client then signals it's ready for results by calling Start().
Change the avahi_s_service_resolver_prepare() method to call avahi_s_record_browser_prepare() for the SRV and TXT records rather than avahi_s_record_browser_new() which calls avahi_s_service_resolver_start() much too early.
This fixes an intermittent deadlock when using the org.freedesktop.Avahi.Server2 D-Bus interface with GDBus.
Fixes: https://github.com/lathiat/avahi/issues/446
> Emit the ServiceResolver Found/Failure signals at the correct time

- fuzz/oss-fuzz.sh
When the fuzz targets were moved upstream they were renamed to avoid running into issues like
https://github.com/ossf/fuzz-introspector/pull/620. The corpora accumulated by OSS-Fuzz couldn't be renamed though so the idea was to download the old corpora and use them as seed corpora. It worked but now that the old corpora are gone the script can no longer download them and CIFuzz is failing.
CIFuzz downloads the new corpora automatically anyway so it's no longer necessary to keep that part.
> fuzz: no longer download public OSS-Fuzz corpora

- .github/workflows/build.sh
- .github/workflows/build.yml
- .github/workflows/smoke-tests.sh
- avahi-compat-howl/Makefile.am
to make sure avahi more or less works.
It fully installs avahi, starts the service, runs the avahi utils, sends signals, exercises the simple protocol, pokes the D-Bus interface with dfuzzer and runs several tests that can't be run as unit tests. Apart from plain builds it also runs that under ASan/UBSan and Valgrind. Currently it exercises exactly half of the Avahi code base: https://coveralls.io/builds/62803033.
`make distcheck` is run to make sure the tarball is more or less releasable.
> [CI] add a smoke test

- avahi-common/alternative-test.c
- avahi-common/alternative.c
Previously, alternative host name we created might have ended up being invalid. We consider single label names with trailing dot valid, e.g. "foo.". However, multi label host names are not valid. Hence, for valid host name "foo."  we created alternative "foo.-2" which was invalid and crashed the daemon.
Fixes #451
CVE-2023-38473
> common: reject single label host names with unescaped trailing dot

- avahi-client/client-test.c
- avahi-daemon/dbus-entry-group.c
> core: make sure there is rdata to process before parsing it

- avahi-core/rr.c
- fuzz/fuzz-consume-key.c
- fuzz/fuzz-consume-record.c
It fixes the crash spotted https://github.com/lathiat/avahi/pull/490#issuecomment-1773019619.
The fuzz target was updated to exercise those code paths (among other things). Without this commit it crashes with
```sh
fuzz-consume-record: malloc.c:250: void *avahi_memdup(const void *, size_t): Assertion `s' failed.
==72869== ERROR: libFuzzer: deadly signal
#0 0x5031b5 in __sanitizer_print_stack_trace (avahi/out/fuzz-consume-record+0x5031b5) (BuildId: 69840d811c9ba9f74eea21e34786a2005c5dcc06)
#1 0x45cd6c in fuzzer::PrintStackTrace() (avahi/out/fuzz-consume-record+0x45cd6c) (BuildId: 69840d811c9ba9f74eea21e34786a2005c5dcc06)
#2 0x441c47 in fuzzer::Fuzzer::CrashCallback() (out/fuzz-consume-record+0x441c47) (BuildId: 69840d811c9ba9f74eea21e34786a2005c5dcc06)
#3 0x7f189e97ebaf …
```
> core: copy resource records with zero-length rdata properly

- avahi-core/server.c
Previously we could create invalid escape sequence when we split the string on dot. For example, from valid host name "foo\\.bar" we have created invalid name "foo\\" and tried to set that as the host name which crashed the daemon.
Fixes #453
CVE-2023-38471
> core: extract host name using avahi_unescape_label()

- .github/workflows/smoke-tests.sh
- avahi-core/server.c
It's a follow-up to 894f085f402e023a98cbb6f5a3d117bd88d93b09
> core: return errors from avahi_server_set_host_name properly

- .github/workflows/smoke-tests.sh
- avahi-client/client-test.c
- avahi-core/rr.c
Closes https://github.com/lathiat/avahi/issues/455
CVE-2023-38469
The tests were updated to make sure overly long TXT RRs no longer crash avahi.
> core: reject overly long TXT resource records

- examples/core-publish-service.c
server_callback() follows logic to handle AVAHI_SERVER_COLLISION and AVAHI_SERVER_REGISTERING states with an unregister of the service group, but does not reset the pointer to the group to NULL. Added a avahi_s_entry_group_free(group) and reset of the pointer to NULL to ensure the re-registration succeeds.
This is to resolve issue #135.
> Fix logic error in server_callback()

- .github/workflows/build.sh
to prevent avahi from failing to start with
```
avahi-daemon[23549]: avahi-daemon: starting up: symbol lookup error: /lib/libavahi-core.so.7: undefined symbol: avahi_now
```
when the system libraries get mixed up with the newly built libraries.
(It was spotted in a PR where the libcommon library was pulled as a dependency somewhere and the smoke test failed because of that)
> ci: put the libraries in the right place

- avahi-core/dns-test.c
- avahi-core/rr.c
- fuzz/fuzz-consume-record.c
RRs where types are unknown to avahi can't be passed to
lexicographical_memcmp directly because it doesn't expect NULL pointers
and crashes. This patch prevents it from crashing by treating those NULL
pointers as empty strings and returning -1, 0 or 1. It in turn prevents
avahi from crashing on receiving probes with zero-length rdata if
unusual RRs have ever been added using avahi_entry_group_add_record.
This patch also fixes a bug where RRs with no remaining bytes were
deemed lexicographically later even though according to
https://datatracker.ietf.org/doc/html/rfc6762#section-8.2
The bytes of the raw uncompressed rdata are compared ...
until a byte is found whose value is greater than that of its counterpart
... or one of the resource records runs out of rdata (in which case,
the …
> core: compare RRs with zero-length rdata correctly

- avahi-autoipd/Makefile.am
- avahi-daemon/Makefile.am
- avahi-daemon/avahi-daemon.socket.in
- avahi-dnsconfd/Makefile.am
- configure.ac
Switching to a standard variable will allow to simplify downstream packages. The variable was introduced in Autoconf 2.70: https://www.gnu.org/prep/standards/html_node/Directory-Variables.html
Fixes: https://github.com/lathiat/avahi/issues/137
> build: Use runstatedir instead home-brewn variable

- avahi-common/domain-test.c
- avahi-common/utf8-test.c
- fuzz/fuzz-packet.c
- fuzz/oss-fuzz.sh
to exercise message compression/decompression and various various getters/setters.
I also extracted a couple of commits related to the utf8 tests from https://github.com/lathiat/avahi/pull/481.
> fuzz: fuzz full DNS packets

- avahi-common/alternative-test.c
- avahi-common/domain.c
- fuzz/fuzz-domain.c
All the functions receiving service names expect them to be UTF-8. When they aren't those functions can crash. For example here's how avahi_alternative_service_name crashed without this patch:
```
alternative-test: alternative.c:44: drop_incomplete_utf8: Assertion `*e & 128' failed.
#0  0x00007ffff76b0884 in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff765fafe in raise () from /lib64/libc.so.6
#2  0x00007ffff764887f in abort () from /lib64/libc.so.6
#3  0x00007ffff764879b in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00007ffff7658187 in __assert_fail () from /lib64/libc.so.6
#5  0x000000000040257b in drop_incomplete_utf8 (c=0x60200003bed0 "\301\n") at alternative.c:44
#6  0x00000000004033b2 in avahi_alternative_service_name (s=0x40ff00 "\301\n") at …
```
> common: make avahi_is_valid_service_name reject non-UTF-8 service names

- avahi-core/server.c
Fixes the following cppcheck warning:
```
avahi-core/server.c:1798:8: style: Suspicious condition (assignment + comparison); Clarify expression with parentheses. [clarifyCondition]
if ((ret = avahi_service_name_join(n, sizeof(n), name, type, domain) < 0))
^
```
It makes avahi_server_get_group_of_service set the error code correctly.
Closes https://github.com/lathiat/avahi/issues/205
> core: clarify suspicious condition with parentheses

- .github/workflows/smoke-tests.sh
- avahi-common/domain-test.c
- avahi-common/domain.c
- avahi-core/browse-service-type.c
- avahi-core/browse-service.c
- fuzz/fuzz-packet.c
It was technically a DOS allowing packets with service names like "bogus.service.local" to bring down `avahi-browse -a`. In practice it was usually triggered by misconfigured smart devices but it isn't that hard to forge packets like that and send them deliberately.
The tests are added to make sure invalid service names are rejected and valid service names keep working. The fuzz target is updated to make sure that avahi_service_name_split always supplies valid arguments to avahi_service_name_join. avahi now logs what exactly it fails to split
```
avahi-daemon[176]: Failed to split service name '0.1.9.1.8.8.e.f.f.f.f.a.a.1.4.7.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa'
avahi-daemon[176]: Failed to split service name 'bogus\032.\032\209\129\208\181\209\128\208\178\208\184\209\129.local' …
```
> core: no longer supply bogus services to callbacks

- .github/workflows/cifuzz.yml
It should already work but I'd wait for https://github.com/google/oss-fuzz/pull/11312 to get merged.
> ci: switch CIFuzz to avahi/avahi

- avahi-core/socket.c
I have seen a log of failed attempts to send multicast responses to localhost interface, which is missing multicast flag. Make it more obvious which interface is responsible by logging fail from sendmsg with at least interface number included.
> Log also interface number when sendmsg has failed

- .github/workflows/build.sh
- .github/workflows/build.yml
- .github/workflows/smoke-tests.sh
When avahi-daemon fails under ASan/UBSan the tests trying to reach it via D-Bus start to fail too with cryptic error messages and without ASan reports it's hard to tell what exactly fails.
This patch is prompted by https://github.com/avahi/avahi/pull/551 where the smoke test failed with
```
** (process:23892): WARNING **: 10:26:43.529: Error initializing Avahi: Daemon not running
glib-integration: client.c:626: void avahi_client_free(AvahiClient *): Assertion `client' failed.
```
without any way to figure out what went wrong.
With this patch applied the following backtrace would have been shown:
```
avahi-daemon[23694]: browse.c: Found CNAME loop on interface 2, proto 1, query cname0.local        IN        AAAA
avahi-daemon[23694]: browse.c: Found CNAME loop on interface 2, proto 1, query …
```
> CI: always look for ASan/UBSan reports

- .github/workflows/build.yml
It's a draft because Coveralls doesn't have access to the repository yet
Depends on https://github.com/avahi/avahi/issues/540
> ci: switch coverage to avahi/avahi

- fuzz/fuzz-strlst.c
- fuzz/oss-fuzz.sh
OSS-Fuzz doesn't fully support aarch64 yet
https://github.com/google/oss-fuzz/issues/8164 but the toolchain already
provides an easy way to build and run the fuzz targets on aarch64 with
```
./infra/helper.py ... --architecture=aarch64 ...
```
This patch prevents avahi from failing to compile there by avoiding
installing the "386" dependencies when they aren't necessary. All the
build dependencies are brought upstream to make it possible to change
them upstream without having to send patches to OSS-Fuzz.
The script also dumps build logs when configure fails to make it
easier to debug build failures.
The strlist fuzz target was updated to make sure "printable" DNS-SD key/value pairs are UTF-8.
Those strings are consumed in various places and it's generally expected
that they are UTF-8. …
> fuzz: make the build script compatible with aarch64 

- man/avahi-daemon.conf.5.xml.in
- man/avahi-resolve.1.xml.in
Current description for enable-wide-area=yes doesn't mention the impact for reverse lookup, it caused me sometime to figure out the impact, update the description to explicitly mention that enable-wide-area=yes also cause reverse lookup to use unicast DNS.
> Update description for enable-wide-area to mention impact for avahi-resolve-address

- README
- docs/NEWS
- docs/README
- docs/TODO
- man/avahi-daemon.conf.5.xml.in
to make it easier to find them.
The second commit removes obsolete content from docs/README. It was extracted from https://github.com/avahi/avahi/pull/481.
> docs: add links to coverity, oss-fuzz, coverage and codespell reports

- avahi-daemon/simple-protocol.c
MDNS protocol specifies maximal hostname length used is 255 characters plus terminating zero. One label has maximal 63 characters, but full hostname can be longer. Ensure we have space for any hostname allowed by the protocol.
> Increase max hostname specified in simple-protocol

- .github/workflows/smoke-tests.sh
and add it to the corpus used by radamsa too.
> smoke-test: pass overly long hostname to RESOLVE-HOSTNAME

- .packit.yml
It already works:
https://github.com/evverx/avahi/pull/3/checks?check_run_id=19440388533
https://copr.fedorainfracloud.org/coprs/packit/evverx-avahi-3/builds/
Depends on https://github.com/avahi/avahi/issues/540
> ci: build avahi on aarch64, i386, ppc64le, s390x, x86_64 on PRs

- .github/workflows/smoke-tests.sh
- avahi-common/alternative.c
- fuzz/oss-fuzz.sh
* common: fix int overflow in avahi_alternative_*_name (extracted from https://github.com/avahi/avahi/pull/547)
* smoke-test: poke GetAlternative*Name
> fuzz: turn on pointer-overflow and alignment checks 

- avahi-compat-libdns_sd/compat.c
Fixes segfault on shutdown. On client failure, generic_client_callback function simply checks if all the callback functions are non-zero and triggers the callback. This change sets the callback function memory to NULL and prevents the application from thinking that a callback has been installed.
> libdns_sd: Use allocator with memory set to zero

- .github/workflows/build.sh
- .github/workflows/smoke-tests.sh
and also run the compat-libdns_sd test when avahi is up and running.
Prompted by https://github.com/avahi/avahi/issues/573 and https://github.com/avahi/avahi/pull/569.
https://coveralls.io/builds/65967012
> smoke-test: unicast responses

- .github/workflows/smoke-tests.sh
- avahi-utils/avahi-browse.c
Service resolvers kept outside of the client have to be freed and
removed from the list of resolvers kept in the client before the client
itself is freed to prevent them from being freed twice.
Closes https://github.com/avahi/avahi/issues/534
smoke-test: more tests with AVAHI_CLIENT_NO_FAIL: https://coveralls.io/builds/65988431
> avahi-utils: fix use-after-free in avahi-browse

- avahi-daemon/avahi-daemon.conf
In its current form it doesn't interact with mDNS well. For example services advertised over mDNS where PTR RRs point "_services._dns-sd._udp.local" to unresolvable wide-area domain names bring down mDNS browsers. DNS isn't supported well either. For example responses larger than 512 bytes aren't supported, all the queries come from the same UDP port and so on. All in all in its current form it isn't something that should be enabled by default or picked up accidentally by packages downstream.
It reverts the part of 2c453196ee040e17e357f3431b0647391c88d616 where that feature was turned on.
> avahi-daemon.conf: turn off wide-area

- avahi-daemon/avahi-daemon.conf
- man/avahi-daemon.conf.5.xml.in
Ideally this knob should be revisited but given that it was introduced more than 10 years ago it is probably already used in its current form and can't be changed without breaking something somewhere.
It's a follow-up to 147cdce70b22ae7cee9fb4fe123db40952f31c9e
Closes https://github.com/avahi/avahi/issues/365
> man: be more specific about host-name-from-machine-id

- avahi-common/domain-test.c
- avahi-common/domain.c
- avahi-core/browse-service-type.c
- avahi-core/browse-service.c
Accodring to https://datatracker.ietf.org/doc/html/rfc6763#section-9
```
A DNS query for
PTR records with the name "_services._dns-sd._udp.<Domain>" yields a
set of PTR records, where the rdata of each PTR record is the two-
label <Service> name, plus the same domain, e.g.,
"_http._tcp.<Domain>".
```
and according to https://datatracker.ietf.org/doc/html/rfc6763#section-7
```
The <Service> portion of a Service Instance Name consists of a pair
of DNS labels, following the convention already established for SRV
records [RFC2782].
```
With this patch applied avahi rejects service names violating those
rules. It prevents avahi-browse from showing one-label service names and
also prevents avahi-discover-standalone from crashing on receiving
announcements with non-compliant PTR resource …
> core: reject more service names violating RFC6763

- .github/workflows/build.yml
- .github/workflows/linter.yml
with https://github.com/rhysd/actionlint?tab=readme-ov-file#actionlint to make it easier to add/change/review GH Actions.
Mostly in preparation for an action sending data to Coverity Scan.
Related to https://github.com/avahi/avahi/issues/540
> CI: lint GH Actions

- .github/workflows/coverity.sh
- .github/workflows/coverity.yml
to keep reports at https://scan.coverity.com/projects/avahi-daemon up to date automatically.
> CI: add an action sending data to Coverity Scan

- avahi-discover-standalone/main.c
Include useful message printing the reason of the failure. Useful especially when the file is not in correct path.
This were rejected in #408, but I think this part alone should be merged.
> Report fatal error when UI file were not loaded

- avahi-python/avahi/ServiceTypeDatabase.py.in
Corrects 
```python
/usr/lib/python3.12/site-packages/avahi/ServiceTypeDatabase.py:98: SyntaxWarning: invalid escape sequence '\.'
if not re.search('_[a-zA-Z0-9-]+\._[a-zA-Z0-9-]+', key):
```
> avahi-discover: Fix invalid escape sequences

- avahi-client.pc.in
This fixes static linking of avahi-client using pkg-config, by telling pkg-config to also link with dbus, since static libraries don't carry their own dependency information.
> Add dbus-1 to avahi-client Requires.private

- .github/workflows/coverity.sh
- .github/workflows/coverity.yml
to prevent it from sending notifications to the authors of the latest commits.
That logic came from some internal script and doesn't make sense upstream.
The idea was borrowed from https://github.com/bus1/dbus-broker/pull/363
> ci: forward Coverity Scan notifications to COVERITY_SCAN_NOTIFICATION_EMAIL

- fuzz/fuzz-ini-file-parser.c
- fuzz/oss-fuzz.sh
and also prevent bash from complaining about unbound FUZZING_ENGINE variable.
Fixes:
```
+ mkdir -p /home/vagrant/avahi/out
+ export LIB_FUZZING_ENGINE=-fsanitize=fuzzer
+ LIB_FUZZING_ENGINE=-fsanitize=fuzzer
./fuzz/oss-fuzz.sh: line 47: FUZZING_ENGINE: unbound variable
```
It's a follow-up to d2aac837a47ea180e5b5a77c568841d77e92b57e
> ci: fuzz ini parser

- .github/SECURITY.md
- .github/workflows/build.sh
- docs/INSTALL
to make it actually work on Debian/Ubuntu. Other topics like turning
off D-Bus or running it on non-systemd systems should probably be
documented elsewhere eventually too.
The CI script is updated too to make sure the configure options
mentioned in INSTALL keep working on Ubuntu.
Addresses https://github.com/avahi/avahi/issues/612
and add SECURITY.md pointing to the "Report a vulnerability" tab. People reporting
vulnerabilities are usually aware of that GitHub feature but it
shouldn't hurt to mention it explicitly. It's also shown
when issues are opened.
> docs: modernize INSTALL

- README
to make it easier to find it.
It's a follow-up to 45378fb97eff8bc4d2b43c471fb10410cb1b7073
> README: point to the Fedora Weblate instance

- avahi-core/log.c
- avahi-daemon/ini-file-parser.c
This is particularly important for reflect-filters, which can be lengthy in real-world use.
> Increase length limit on input lines.

- examples/client-publish-service.c
- examples/core-publish-service.c
A badly placed closing bracket was assigning a comparison to the ret value, instead of the real returned value. The conditional still worked this way, but the fprintf message would be wrong as the strerror value "ret" would always be 1, and not the real returned value.
> Fix conditional typo on client-publish-service.c

- .packit.yml
It's prompted by 8e77303a9aed6888677a2bd234cfde5b11faca37, 32fba39e116667bbd9e950b2dd7abd70956b90e8 and
16b6397f15b28ec80d57a892a7f982aad7630e0f and should help to catch issues like that automatically.
See https://github.com/avahi/avahi/pull/641.
> Enable style checker in cppcheck in Packit OpenScanHub configurations

- avahi-common/Makefile.am
- avahi-python/avahi-discover/Makefile.am
- avahi-ui/Makefile.am
- configure.ac
to get avahi to look for the locales in the right place.
DATADIRNAME is no longer set so avahilocaledir points to non-existent directories like `/usr//locale`. That bespoke variable was introduced back in 2007 and can safely be replaced with localedir (which was introduced in Autoconf 2.59c (2006-04-12)).
Closes: https://github.com/avahi/avahi/issues/644
> build-system: switch to localedir

- avahi-core/wide-area.c
- configure.ac
Use proper randomization for next transaction id. Do not use naive IDs.
> Randomize transaction IDs in wide area queries
