avahi-discover-standalone/main.c
https://developer.gnome.org/gtk3/stable/GtkBuilder.html#gtk-builder-set-translation-domain
=> Sets the translation domain of builder

avahi-discover-standalone/main.c, avahi-python/avahi-discover/avahi-discover.py
https://bugzilla.redhat.com/show_bug.cgi?id=1270535
=> Set translation domain py

avahi-compat-libdns_sd/warn.c
https://bugzilla.opensuse.org/show_bug.cgi?id=914298
=> trivial: fix URL posted in debug messages

service-type-database/service-types
Add the ipps protocol, advertised by e.g. CUPS.
=> database: add Secure Internet Printer

service-type-database/service-types
"Posta - POP3" seems to be Italian, mark it as such.
=> database: fix duplicate service

man/avahi-dnsconfd.8.xml.in
Fix file name of action script.
=> Fix file name in man page (avahi-dnsconfd.8.xml.in)

service-type-database/service-types
http://xpra.org/trac/ticket/731
The original ticket I had created for avahi is now 404:
http://avahi.org/ticket/368
=> add Xpra service type

po/cs.po, po/zh_CN.po
=> Fix XML tags in Czech and Chinese Simplified translations

.travis.yml, avahi-python/avahi-discover/Makefile.am, avahi-python/avahi-discover/avahi-discover.py, configure.ac
The code can still run with Python 2 as well.
I didn't work out all the autotools stuff, so I just tweaked the `@substitution@` bits by hand so I could run the code to test it.
=> Update avahi-discover code to Gtk 3 and Python 3

configure.ac
Signed-off-by: Jussi Kukkonen <jussi.kukkonen@intel.com>
Signed-off-by: Dengke Du <dengke.du@windriver.com>
=> configure.ac: install GtkBuilder interface files for GTK+3 too

po/ro.po
Added the latest updates to the Romanian translation contributed by the members of the Gnome Romanian Translation Team.
The workflow can be followed here: https://l10n.gnome.org/vertimus/avahi/master/po/ro
=> Updated Romanian Translation

avahi-client/lookup.h
Fully describe the behavior of browser, resolver and associated
callbacks with regard to query and address protocols.
=> avahi_service_resolver_new: more documentation

avahi-daemon/dbus-util.c
=> Do not send out OK reply when client sets NO_REPLY_REQUESTED

avahi-python/avahi-bookmarks.in
This should work with Python 2 as well, but I've only tested it with Python 3.
=> Make avahi-bookmarks Python3 compatible

avahi-core/dns.c
#267  the solution;
I have test it's effective.
=> modify fuzz test err

po/ro.po
I am the coordinator of the Gnome Romanian Team and we have this translation update ready.
Our avahi-work can be tracked here: https://l10n.gnome.org/vertimus/avahi/master/po/ro/
=> Updated the Romanian Translation

man/avahi-daemon.conf.5.xml.in, man/avahi-publish.1.xml.in
=> Fix document for avahi-daemon.conf and avahi-publish

man/avahi-daemon.8.xml.in
Tripped up a couple times reading the man page.
I'm reasonably sure this is the right spot for these, but wouldn't be surprised if I'm wrong, as this file hasn't been touched in 13 years :sweat_smile:
=> Minor text updates to avahi-daemon.8.xml.in

avahi-python/avahi-bookmarks.in, avahi-python/avahi-discover/avahi-discover.py
=> Correct error DBusGMainLoop in avahi-bookmarks

fuzz/fuzz-domain.c
to catch issues like https://github.com/lathiat/avahi/issues/451 and https://github.com/lathiat/avahi/issues/487.
Waiting for https://github.com/lathiat/avahi/pull/486
=> fuzz avahi_alternative_host_name

.github/workflows/build.sh, .github/workflows/smoke-tests.sh
Prompted by https://github.com/lathiat/avahi/pull/330 and https://github.com/lathiat/avahi/issues/338.
=> smoke-test: poke the simple protocol with radamsa

.github/workflows/build.sh, .github/workflows/smoke-tests.sh, avahi-daemon/Makefile.am, avahi-daemon/main.c, avahi-daemon/sd-daemon.c, avahi-daemon/sd-daemon.h, avahi-daemon/simple-protocol.c, configure.ac, fuzz/oss-fuzz.sh
systemd no longer receives notifications: https://github.com/lathiat/avahi/pull/459#issuecomment-1791477356
The regression test is added to make sure that systemd actually receives notifications.
=> Revert "Stop using embedded copy of sd-daemon.{c,h} and use libsystemd instead"

fuzz/oss-fuzz.sh
to make it easier to reproduce bugs locally.
=> fuzz: make it possible to build the fuzz targets without docker

.github/workflows/build.sh, .github/workflows/smoke-tests.sh
record browser, domain browser, dns server browser and some other things.
https://coveralls.io/builds/65623826
=> smoke-test: cover sync address/hostname/service resolvers

.packit.yml
=> ci: build avahi on various arches on commits too

po/avahi.pot
to integrate avahi into https://translate.fedoraproject.org/projects/avahi
Related to https://github.com/avahi/avahi/issues/603 and https://pagure.io/fedora-l10n/tickets/issue/40.
=> po: add avahi.pot

Makefile.am, avahi-core/dns.h, avahi-core/wide-area.h
Expand a bit documentation of core wide-area API.
=> Extend doxygen dns.h and wide-area.h API

.github/workflows/build.sh, .github/workflows/smoke-tests.sh, autogen.sh
=> Replace shebang with a portable one

docs/README
=> Tidy up the dependencies section of README
